apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - mountPath: /var/www/html/
          name: wp
        - mountPath: /etc/nginx/conf.d/
          name: conf
        ports:
        - containerPort: 80
      - name: php-fpm
        image: hiakki/php7.3-fpm_mysql
        volumeMounts:
        - mountPath: /var/www/html/
          name: wp
        ports:
        - containerPort: 9000
      volumes:
      - name: wp
        hostPath:
          path: /root/website/wordpress
      - name: conf
        hostPath:
          path: /root/website/nginx/
